apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ng-jp-dp
  name: ng-jp-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng-jp-dp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ng-jp-dp
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
